### ISSUE TITLE
Change MySQL MyISAM to InnoDB

### ISSUE THREAD

**Issue by GoogleCodeExporter** [halalaninitiative/halalan#71]
```
Improvement to the aging Halalan database.
```

Original issue reported on code.google.com by `waldemar...@gmail.com` on 16 Jun 2010 at 7:34

**Comment by GoogleCodeExporter** [comment]
```
Testing...
```

Original comment by `waldemar...@gmail.com` on 23 Jun 2010 at 3:04
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `waldemar...@gmail.com` on 23 Jun 2010 at 3:04
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Add table for logging purposes.
```

Original comment by `waldemar...@gmail.com` on 24 Jun 2010 at 3:22

**Comment by GoogleCodeExporter** [comment]
```
Redesinging DB...
```

Original comment by `waldemar...@gmail.com` on 9 Jul 2010 at 8:55
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
*redesigning
```

Original comment by `waldemar...@gmail.com` on 9 Jul 2010 at 8:57

**Comment by GoogleCodeExporter** [comment]
```
Redesigning DB...
```

Original comment by `waldemar...@gmail.com` on 9 Jul 2010 at 9:01

**Comment by GoogleCodeExporter** [comment]
Original comment by `waldemar...@gmail.com` on 21 Jul 2010 at 2:56
- Changed state: **Fixed**

**Comment by waldemarbautista** [comment]
Reopning.

**Comment by waldemarbautista** [comment]
Done in 55f730be407c6ef4031442d3b2b7fc7d09a6daf1.
