### ISSUE TITLE
Change License to MIT License

### ISSUE THREAD

**Issue by GoogleCodeExporter** [halalaninitiative/halalan#81]
```
As discussed in halalan-dev mailing list, the license of Halalan will be 
changed from GPLv3 to MIT.  Update all files concerned to reflect this change.
```

Original issue reported on code.google.com by `waldemar...@gmail.com` on 25 Mar 2012 at 4:15

**Comment by GoogleCodeExporter** [comment]
Original comment by `aicapa...@gmail.com` on 16 Apr 2012 at 8:58
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
Original comment by `aicapa...@gmail.com` on 18 Apr 2012 at 9:07
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `waldemar...@gmail.com` on 24 Jun 2012 at 8:34
- Changed state: **Verified**

**Comment by waldemarbautista** [comment]
Redo this.
